import type { MenuItem } from "./types";

// Giá quy đổi từ yen (ảnh menu): 1 yen ≈ 200 VND (hiển thị đẹp, có thể đổi tỉ lệ)
const Y = (y: number) => y * 200;

export const menuItems: MenuItem[] = [
  // --- つけ麺 --- (ảnh menu: 1000/1100/1200/1300)
  {
    id: "tsukemen-150-200",
    name: "つけ麺 150g・200g",
    nameVi: "Tsukemen 150g・200g",
    description: "スープは同量です。替え玉できません。",
    category: "tsukemen",
    portionChoice: "150-200",
    price: Y(1000),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tsukemen-300",
    name: "つけ麺 300g",
    nameVi: "Tsukemen 300g",
    description: "スープは同量です。替え玉できません。",
    category: "tsukemen",
    price: Y(1100),
    highlight: "popular",
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tsukemen-400",
    name: "つけ麺 400g",
    nameVi: "Tsukemen 400g",
    description: "スープは同量です。替え玉できません。",
    category: "tsukemen",
    price: Y(1200),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tsukemen-500",
    name: "つけ麺 500g",
    nameVi: "Tsukemen 500g",
    description:
      "スープは同量です。替え玉できません。おかわりや追加をご希望の場合は、メニューからお気軽に追加でご注文ください。",
    category: "tsukemen",
    price: Y(1300),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tsukemen-500over",
    name: "つけ麺 500g以上",
    nameVi: "Tsukemen 500g+",
    description:
      "500gメニューより大盛り。スープは同量です。替え玉できません。おかわりや追加をご希望の場合は、メニューからお気軽に追加でご注文ください。",
    category: "tsukemen",
    portionChoice: "500over-grams",
    price: Y(1300),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  // --- 多聞つけ麺 --- (ảnh menu: 1100/1200/1300/1400)
  {
    id: "tamon-150-200",
    name: "多聞つけ麺 150g・200g",
    nameVi: "Tamon Tsukemen 150g・200g",
    description: "スープは同量です。替え玉できません。",
    category: "tamon_tsukemen",
    portionChoice: "150-200",
    price: Y(1100),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tamon-300",
    name: "多聞つけ麺 300g",
    nameVi: "Tamon Tsukemen 300g",
    description: "スープは同量です。替え玉できません。",
    category: "tamon_tsukemen",
    price: Y(1200),
    highlight: "signature",
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tamon-400",
    name: "多聞つけ麺 400g",
    nameVi: "Tamon Tsukemen 400g",
    description: "スープは同量です。替え玉できません。",
    category: "tamon_tsukemen",
    price: Y(1300),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tamon-500",
    name: "多聞つけ麺 500g",
    nameVi: "Tamon Tsukemen 500g",
    description:
      "スープは同量です。替え玉できません。おかわりや追加をご希望の場合は、メニューからお気軽に追加でご注文ください。",
    category: "tamon_tsukemen",
    price: Y(1400),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "tamon-500over",
    name: "多聞つけ麺 500g以上",
    nameVi: "Tamon Tsukemen 500g+",
    description:
      "500gメニューより大盛り。スープは同量です。替え玉できません。おかわりや追加をご希望の場合は、メニューからお気軽に追加でご注文ください。",
    category: "tamon_tsukemen",
    portionChoice: "500over-grams",
    price: Y(1400),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  // --- 追加スープ ---
  {
    id: "extra-soup",
    name: "追加スープ",
    nameVi: "Extra Soup",
    category: "extra",
    price: Y(400),
    options: [],
  },
  // --- ラーメン --- (ảnh menu: 並950円 大1060円、替玉110円)
  {
    id: "ramen-paitan-nami",
    name: "ラーメン (魚介鶏パイタン醤油) 並",
    nameVi: "Ramen (Seafood Chicken Paitan Shoyu) Regular",
    description: "1玉130g",
    category: "ramen",
    price: Y(950),
    highlight: "recommended",
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "ramen-paitan-large",
    name: "ラーメン (魚介鶏パイタン醤油) 大",
    nameVi: "Ramen (Seafood Chicken Paitan Shoyu) Large",
    description: "2玉",
    category: "ramen",
    price: Y(1060),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "shoyu-ramen-nami",
    name: "しょうゆラーメン 並",
    nameVi: "Shoyu Ramen Regular",
    description: "1玉130g",
    category: "ramen",
    price: Y(950),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  {
    id: "shoyu-ramen-large",
    name: "しょうゆラーメン 大",
    nameVi: "Shoyu Ramen Large",
    description: "2玉",
    category: "ramen",
    price: Y(1060),
    options: [
      { id: "ajitama", name: "味玉", nameVi: "Ajitama (Seasoned Egg)", price: Y(110), type: "topping" },
      { id: "menma", name: "メンマ", nameVi: "Menma (Bamboo Shoots)", price: Y(150), type: "topping" },
      { id: "chashu", name: "チャーシュー (3枚)", nameVi: "Chashu (3 slices)", price: Y(360), type: "topping" },
    ],
  },
  // --- 替玉 ---
  {
    id: "kaedama",
    name: "替玉",
    nameVi: "Extra Noodles (Kaedama)",
    description: "ラーメンの麺は1玉130gです。",
    category: "kaedama",
    price: Y(110),
    options: [],
  },
  // --- トッピング --- (ảnh menu: たまご110、メンマ150、チャーシュー(3枚)360、おつまみセット500)
  {
    id: "ajitama",
    name: "味玉",
    nameVi: "Ajitama (Seasoned Egg)",
    category: "topping",
    price: Y(110),
    options: [],
  },
  {
    id: "menma",
    name: "メンマ",
    nameVi: "Menma (Bamboo Shoots)",
    category: "topping",
    price: Y(150),
    options: [],
  },
  {
    id: "chashu",
    name: "チャーシュー (3枚)",
    nameVi: "Chashu (3 slices)",
    category: "topping",
    price: Y(360),
    options: [],
  },
  {
    id: "otsumami-set",
    name: "おつまみセット(味玉・メンマ・チャーシュー)",
    nameVi: "Snack Set (Ajitama, Menma, Chashu)",
    description: "全部頼むならこちらがお得!",
    category: "topping",
    price: Y(500),
    options: [],
  },
  // --- ライス ---
  {
    id: "rice-small",
    name: "ライス 小",
    nameVi: "Rice Small",
    category: "rice",
    price: Y(130),
    options: [],
  },
  {
    id: "rice-medium",
    name: "ライス 中",
    nameVi: "Rice Medium",
    category: "rice",
    price: Y(200),
    options: [],
  },
  {
    id: "rice-large",
    name: "ライス 大",
    nameVi: "Rice Large",
    category: "rice",
    price: Y(250),
    options: [],
  },
  // --- ぎょうざ (Gyoza) --- (ảnh menu: 6コ400、しそ5コ500、チーズ500)
  {
    id: "gyoza-6",
    name: "餃子 (6個)",
    nameVi: "Gyoza (6 pcs)",
    category: "gyoza",
    price: Y(400),
    options: [],
  },
  {
    id: "shiso-gyoza",
    name: "しそ餃子 (5個)",
    nameVi: "Shiso Gyoza (5 pcs)",
    category: "gyoza",
    price: Y(500),
    options: [],
  },
  {
    id: "cheese-gyoza",
    name: "チーズ餃子 (5個)",
    nameVi: "Cheese Gyoza (5 pcs)",
    category: "gyoza",
    price: Y(500),
    options: [],
  },
  // --- ドリンク (Drinks) --- (ảnh menu: 瓶ビール600、ドライゼロ400、チューハイレモン400、ハイボールP400/L450、SUIジンソーダ400、ビアボール450、コーラ250、ウーロン茶250)
  {
    id: "bottle-beer",
    name: "瓶ビール (ラガー・スーパードライ)",
    nameVi: "Bottled Beer (Lager / Super Dry)",
    category: "drink",
    price: Y(600),
    beerVariantChoice: true,
    options: [],
  },
  {
    id: "dry-zero",
    name: "ドライゼロ (ノンアルコール)",
    nameVi: "Dry Zero (Non-alcoholic)",
    category: "drink",
    price: Y(400),
    options: [],
  },
  {
    id: "chuhai-lemon",
    name: "チューハイ レモン",
    nameVi: "Chuhai Lemon",
    category: "drink",
    price: Y(400),
    options: [],
  },
  {
    id: "highball",
    name: "ハイボール（プレーン／レモン）",
    nameVi: "Highball (Plain / Lemon)",
    category: "drink",
    price: Y(400),
    highballVariantChoice: true,
    options: [],
  },
  {
    id: "sui-gin-soda",
    name: "SUIジンソーダ",
    nameVi: "SUI Gin Soda",
    category: "drink",
    price: Y(400),
    options: [],
  },
  {
    id: "beer-ball",
    name: "ビアボール (レモン・うめ・メロン)",
    nameVi: "Beer Ball (Lemon / Plum / Melon)",
    category: "drink",
    price: Y(450),
    beerBallVariantChoice: true,
    options: [],
  },
  {
    id: "cola",
    name: "コーラ",
    nameVi: "Cola",
    category: "drink",
    price: Y(250),
    options: [],
  },
  {
    id: "oolong-tea",
    name: "ウーロン茶 (ICEのみ)",
    nameVi: "Oolong Tea (ICE only)",
    category: "drink",
    price: Y(250),
    options: [],
  },
];

export const categories = [
  { id: "tsukemen", label: "つけ麺", labelEn: "Tsukemen" },
  { id: "tamon_tsukemen", label: "多聞つけ麺", labelEn: "Tamon Tsukemen" },
  { id: "extra", label: "追加スープ", labelEn: "Extra Soup" },
  { id: "ramen", label: "ラーメン", labelEn: "Ramen" },
  { id: "kaedama", label: "替玉", labelEn: "Kaedama" },
  { id: "topping", label: "トッピング", labelEn: "Toppings" },
  { id: "rice", label: "ライス", labelEn: "Rice" },
  { id: "gyoza", label: "ぎょうざ", labelEn: "Gyoza" },
  { id: "drink", label: "ドリンク", labelEn: "Drinks" },
] as const;
