import type { MenuItem } from "./types";

export const menuItems: MenuItem[] = [
  {
    id: "tonkotsu",
    name: "Tonkotsu Ramen",
    nameVi: "Ramen Tonkotsu",
    description: "Nước dùng xương heo ninh 12 tiếng, thịt heo cháy cạnh, trứng lòng đào, rong biển, hành lá.",
    category: "ramen",
    price: 69000,
    defaultSpice: false,
    defaultNoodleFirmness: "medium",
    options: [
      { id: "egg", name: "Extra Egg", nameVi: "Thêm trứng", price: 15000, type: "extra" },
      { id: "chashu", name: "Extra Chashu", nameVi: "Thêm thịt heo", price: 25000, type: "extra" },
      { id: "nori", name: "Extra Nori", nameVi: "Thêm rong biển", price: 8000, type: "topping" },
    ],
  },
  {
    id: "miso",
    name: "Miso Ramen",
    nameVi: "Ramen Miso",
    description: "Nước dùng miso đậm đà, ngô ngọt, bơ, thịt xay, măng.",
    category: "ramen",
    price: 65000,
    defaultSpice: false,
    defaultNoodleFirmness: "medium",
    options: [
      { id: "egg", name: "Extra Egg", nameVi: "Thêm trứng", price: 15000, type: "extra" },
      { id: "corn", name: "Extra Corn", nameVi: "Thêm ngô", price: 10000, type: "topping" },
    ],
  },
  {
    id: "shoyu",
    name: "Shoyu Ramen",
    nameVi: "Ramen Shoyu",
    description: "Nước dùng xương gà pha nước tương, thịt heo mềm, măng, rong biển.",
    category: "ramen",
    price: 62000,
    defaultSpice: false,
    defaultNoodleFirmness: "medium",
    options: [
      { id: "egg", name: "Extra Egg", nameVi: "Thêm trứng", price: 15000, type: "extra" },
      { id: "chashu", name: "Extra Chashu", nameVi: "Thêm thịt heo", price: 25000, type: "extra" },
    ],
  },
  {
    id: "spicy-miso",
    name: "Spicy Miso Ramen",
    nameVi: "Ramen Miso Cay",
    description: "Miso ramen với sốt cay truyền thống, thịt xay, đậu phụ chiên.",
    category: "ramen",
    price: 68000,
    defaultSpice: true,
    defaultNoodleFirmness: "medium",
    options: [
      { id: "egg", name: "Extra Egg", nameVi: "Thêm trứng", price: 15000, type: "extra" },
    ],
  },
  {
    id: "gyoza-6",
    name: "Gyoza (6 pcs)",
    nameVi: "Gyoza (6 miếng)",
    description: "Bánh xếp chiên giòn, nhân thịt heo và rau.",
    category: "side",
    price: 45000,
    options: [],
  },
  {
    id: "karaage",
    name: "Karaage",
    nameVi: "Gà chiên giòn",
    description: "Gà ướp gia vị Nhật, chiên giòn, ăn kèm sốt chanh.",
    category: "side",
    price: 55000,
    options: [],
  },
  {
    id: "edamame",
    name: "Edamame",
    nameVi: "Đậu nành luộc",
    description: "Đậu nành Nhật luộc muối.",
    category: "side",
    price: 25000,
    options: [],
  },
  {
    id: "green-tea",
    name: "Green Tea",
    nameVi: "Trà xanh",
    category: "drink",
    price: 15000,
    options: [],
  },
  {
    id: "ramune",
    name: "Ramune",
    nameVi: "Ramune",
    description: "Soda Nhật truyền thống.",
    category: "drink",
    price: 25000,
    options: [],
  },
  {
    id: "combo-1",
    name: "Combo Solo",
    nameVi: "Combo 1 người",
    description: "1 tô ramen + 1 món phụ + 1 đồ uống.",
    category: "combo",
    price: 99000,
    options: [],
  },
];

export const categories = [
  { id: "ramen", label: "Ramen", labelEn: "Ramen" },
  { id: "side", label: "Món phụ", labelEn: "Sides" },
  { id: "drink", label: "Đồ uống", labelEn: "Drinks" },
  { id: "combo", label: "Combo", labelEn: "Combo" },
] as const;
